services:
  - type: web
    name: emily-bsmart
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: API_BASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: MS_TENANT_ID
        sync: false
      - key: MS_CLIENT_ID
        sync: false
      - key: MS_CLIENT_SECRET
        sync: false
      - key: MS_SENDER_EMAIL
        sync: false
      - key: NOTIFICATION_EMAILS
        sync: false
